%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/inesviolante/Library/CloudStorage/OneDrive-King'sCollegeLondon/Documents/Papers/rsfMRI_TI_Kurtin/StimSensation.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 29-Nov-2024 16:19:12

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:D81";

% Specify column names and types
opts.VariableNames = ["TIDESNumber", "Scan", "ScanNumber", "StimulationSensation"];
opts.VariableTypes = ["categorical", "categorical", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["TIDESNumber", "Scan"], "EmptyFieldRule", "auto");

% Import the data
StimSensation = readtable("C:\Users\dk818\OneDrive - Imperial College London\INS\TIrsfMRI_BrainStateTopologyAndDynamics\GitHub\Inputs\StimSensation.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% Clear baseline session
StimSensation(1:20,:)=[];

%% Some analysis
StimSensation.ScanNumber = categorical(StimSensation.ScanNumber);

lme = fitglme(StimSensation,'StimulationSensation ~ Scan + ScanNumber + (1|TIDESNumber)', 'Distribution','Binomial','link','logit');
anova(lme)

lme2 = fitglme(StimSensation,'StimulationSensation ~ Scan*ScanNumber + (1|TIDESNumber)', 'Distribution','Binomial','link','logit');
anova(lme2)

%% What about accuracy
for ii=1:height(StimSensation)
    if ((StimSensation.Scan(ii)=='Sham') & (StimSensation.StimulationSensation(ii)==0))
        StimSensation.Accuracy(ii) = 1;
    elseif ((StimSensation.Scan(ii)~='Sham') & (StimSensation.StimulationSensation(ii)==1))
        StimSensation.Accuracy(ii) = 1;
    else
        StimSensation.Accuracy(ii) = 0;
    end
end


% Model on accuracy
lme3 = fitglme(StimSensation,'Accuracy ~ Scan + ScanNumber + (1|TIDESNumber)', 'Distribution','Binomial','link','logit');
anova(lme3)
